### ISSUE TITLE
发现个小问题

### ISSUE THREAD

**Issue by xlliang** [xhzengAIB/PopMenu#1]
你好：第一次点击 ，按钮们 显示，这个时候,我轻扫背景 ，就会再次弹出一个，可以一直反复

**Comment by xhzengAIB** [comment]
这个不算是问题吧！只是Demo的使用是新建多个实例，你可以自己进行控制什么时候弹出，什么时候不弹出的吧！

**Comment by abidullah** [comment]
i get this error 
POPVector.h:342:60: Too many arguments provided to function-like macro invocation
