### ISSUE TITLE
如果不用CocoaPods，怎么配置PopMenu呢？

### ISSUE THREAD

**Issue by Insfgg99x** [xhzengAIB/PopMenu#9]
如题，如果不用CocoaPods，怎么配置PopMenu呢？谢谢！

**Comment by HePingLaoSan** [comment]
同问

**Comment by xhzengAIB** [comment]
这里涉及到另外一个第三方库，引入这些文件https://github.com/xhzengAIB/PopMenu/tree/master/PopMenu
和引入https://github.com/xhzengAIB/RealTimeBlur/tree/master/XHRealTimeBlur
然后你包含头文件就可以使用了
